#!/usr/bin/env python3
# scripts/sync-kit.py                                              -*-Python-*-
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
"""Mirror smd::kit::foundation from compile-time-scheme into this repository.

src/smd/forth/foundation/ is adapted by copy from compile-time-scheme's
src/smd/kit/foundation/ (docs/forth-plan-2.md, D2 carried forward; the
durable invariant in AGENTS.md).  The copy is a mirror, not a fork: every
header and test in the kit directory lands here under the same leaf name,
with exactly these mechanical rewrites and nothing else --

  src/smd/kit/foundation/   ->  src/smd/forth/foundation/   (paths, includes)
  smd::kit::foundation      ->  smd::forth::foundation      (namespaces)
  SRC_SMD_KIT_FOUNDATION_   ->  SRC_SMD_FORTH_FOUNDATION_   (include guards)

plus one provenance line after the SPDX line, per AGENTS.md's file-prolog
rule for adapted-by-copy files.  The kit's own prolog narrative is kept
verbatim below that line; it is the file's history and travels with it.

The rewrites lengthen some lines ("forth" is two characters longer than
"kit"), so every mirrored file is then run through this repository's own
clang-format hook -- the one `make lint` runs, via pre-commit -- and the
mirror is what that hook leaves.  Formatting is the one non-textual step,
and it is the same step lint would take, so the copy is stable under lint.

CMakeLists.txt is regenerated from the file list, so a header the kit adds
or drops is picked up without a hand edit.  Files in the destination that
the kit no longer has are deleted.

Usage:

  scripts/sync-kit.py [--scheme PATH] [--check]

--scheme defaults to ~/src/compile-time-scheme/main.  --check rewrites
nothing and exits nonzero if the mirror is out of date, printing the files
that differ; it is how a later step can tell the copy has drifted.
"""

import argparse
import difflib
import os
import re
import subprocess
import sys

ROOT = subprocess.run(["git", "rev-parse", "--show-toplevel"],
                      capture_output=True, text=True, check=True).stdout.strip()

SRC_REL = "src/smd/kit/foundation"
DST_REL = "src/smd/forth/foundation"
DST = os.path.join(ROOT, DST_REL)

REWRITES = [
    ("src/smd/kit/foundation", "src/smd/forth/foundation"),
    ("smd/kit/foundation", "smd/forth/foundation"),
    ("smd::kit::foundation", "smd::forth::foundation"),
    ("SRC_SMD_KIT_FOUNDATION_", "SRC_SMD_FORTH_FOUNDATION_"),
]

PROLOG_PATH_RE = re.compile(r"^// (\S+)( +)(-\*-C\+\+-\*-)$")
SPDX = "// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception"


def rewrite_body(text):
    for old, new in REWRITES:
        text = text.replace(old, new)
    return text


def rewrite_prolog_path(line):
    """Rewrite the canonical-path comment on line 1, keeping its width.

    The kit pads the path so the Emacs mode line ends at a fixed column;
    'forth' is two characters longer than 'kit', so two pad spaces go.
    """
    m = PROLOG_PATH_RE.match(line)
    if not m:
        return line
    path, pad, mode = m.groups()
    new_path = path.replace(SRC_REL, DST_REL)
    delta = len(new_path) - len(path)
    new_pad = " " * max(1, len(pad) - delta)
    return f"// {new_path}{new_pad}{mode}"


def transform(name, text):
    lines = text.split("\n")
    if len(lines) < 2 or lines[1] != SPDX:
        sys.exit(f"{name}: expected SPDX on line 2, got {lines[1]!r}")
    out = [rewrite_prolog_path(lines[0]), SPDX,
           "// Adapted by copy from compile-time-scheme (smd::kit::foundation):",
           f"// {SRC_REL}/{name}"]
    out.extend(rewrite_body(line) for line in lines[2:])
    return "\n".join(out)


CMAKE_TEMPLATE = """\
# src/smd/forth/foundation/CMakeLists.txt                            -*-cmake-*-
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# Generated by scripts/sync-kit.py from the kit's file list; edit the
# script, not this file.

target_sources(
    compile-time-forth.forth
    PUBLIC
        FILE_SET forth_forth_headers
            TYPE HEADERS
            FILES
{headers}
)

if(FORTH_ENABLE_TESTING)
    add_executable(foundation_test)

    target_sources(
        foundation_test
        PRIVATE
{tests}
    )

    target_link_libraries(foundation_test compile-time-forth.forth)
    target_link_libraries(foundation_test Catch2::Catch2WithMain)

    include(Catch)
    catch_discover_tests(foundation_test)
endif()
"""


def cmake_text(headers, tests):
    return CMAKE_TEMPLATE.format(
        headers="\n".join(f"                {h}" for h in headers),
        tests="\n".join(f"            {t}" for t in tests))


def lint_format(paths):
    """Run the repository's clang-format hook on @p paths, in place.

    pre-commit exits nonzero when it modified a file; that is the expected
    outcome here, not a failure, so only a missing tool is fatal.
    """
    cpp = [p for p in paths if not p.endswith("CMakeLists.txt")]
    if not cpp:
        return
    r = subprocess.run(["uv", "run", "--quiet", "pre-commit", "run",
                        "clang-format", "--files", *cpp],
                       cwd=ROOT, capture_output=True, text=True)
    if r.returncode not in (0, 1):
        sys.exit(f"clang-format via pre-commit failed:\n{r.stdout}{r.stderr}")


def formatted(wanted):
    """Return @p wanted with each file's text as the lint hook leaves it.

    Formats scratch copies under .build/ (ignored by git, inside the tree so
    the hook resolves the repository's .clang-format) rather than the
    destination, so a check never writes into src/.
    """
    scratch = os.path.join(ROOT, ".build", "kit-sync-check")
    os.makedirs(scratch, exist_ok=True)
    paths = {}
    for name, text in wanted.items():
        path = os.path.join(scratch, name)
        with open(path, "w", encoding="utf-8") as f:
            f.write(text)
        paths[name] = path
    lint_format(list(paths.values()))
    out = {}
    for name, path in paths.items():
        with open(path, encoding="utf-8") as f:
            out[name] = f.read()
        os.remove(path)
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--scheme",
                    default=os.path.expanduser("~/src/compile-time-scheme/main"))
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    src = os.path.join(args.scheme, SRC_REL)
    if not os.path.isdir(src):
        sys.exit(f"no kit at {src}")

    names = sorted(n for n in os.listdir(src)
                   if n.endswith(".hpp") or n.endswith(".test.cpp"))
    headers = [n for n in names if n.endswith(".hpp")]
    tests = [n for n in names if n.endswith(".test.cpp")]

    wanted = {}
    for name in names:
        with open(os.path.join(src, name), encoding="utf-8") as f:
            wanted[name] = transform(name, f.read())
    wanted["CMakeLists.txt"] = cmake_text(headers, tests)
    wanted = formatted(wanted)

    present = {n for n in os.listdir(DST)
               if n.endswith(".hpp") or n.endswith(".test.cpp")
               or n == "CMakeLists.txt"}
    stale = sorted(present - set(wanted))

    changed = []
    for name, text in wanted.items():
        path = os.path.join(DST, name)
        current = None
        if os.path.exists(path):
            with open(path, encoding="utf-8") as f:
                current = f.read()
        if current != text:
            changed.append((name, current, text))

    if args.check:
        for name, current, text in changed:
            print(f"differs: {DST_REL}/{name}")
            if current is not None:
                sys.stdout.writelines(difflib.unified_diff(
                    current.splitlines(True), text.splitlines(True),
                    f"a/{DST_REL}/{name}", f"b/{DST_REL}/{name}"))
        for name in stale:
            print(f"stale: {DST_REL}/{name}")
        return 1 if (changed or stale) else 0

    for name, _, text in changed:
        with open(os.path.join(DST, name), "w", encoding="utf-8") as f:
            f.write(text)
        print(f"wrote  {DST_REL}/{name}")
    for name in stale:
        os.remove(os.path.join(DST, name))
        print(f"removed {DST_REL}/{name}")
    kit_rev = subprocess.run(["git", "-C", args.scheme, "rev-parse", "HEAD"],
                             capture_output=True, text=True).stdout.strip()
    print(f"mirrored {len(wanted) - 1} files from kit at {kit_rev}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
